### ISSUE TITLE
Update package summary and description on conda-forge

### ISSUE THREAD

**Issue by jsnel** [conda-forge/pyglotaran-feedstock#12]
Currently the [pyglotaran conda-forge package page](https://anaconda.org/conda-forge/pyglotaran) has as its summary:

`The Glotaran fitting engine`

Which is not very descriptive, nor in line with the package description upstream. 

The main [pyglotaran repo](https://github.com/glotaran/pyglotaran) (about) uses the following description, which would also be more suitable here:

`A Python library for Global and Target Analysis of time-resolved spectroscopy data`

Presumably to update the description on the conda-forge page, the [readme.md](https://github.com/conda-forge/pyglotaran-feedstock/blob/master/README.md) file here needs to be updated.

Additionally it would be nice to have something under the "Description" which is currently empty, example screenshot attached below.

![image](https://user-images.githubusercontent.com/3616369/144464596-21a16263-6d14-4714-a26b-16ad0d4fdc1e.png)

**Comment by s-weigand** [comment]
I updated the summary in the `0.7.2` release

**Comment by jsnel** [comment]
Thanks! 

To also update the package description on the conda-forge, we need to add a description in the meta.yaml file [here](https://github.com/conda-forge/pyglotaran-feedstock/blob/main/recipe/meta.yaml#L54-L61).

Example [here](https://github.com/conda-forge/spaghetti-feedstock/blob/main/recipe/meta.yaml#L48-L54) - rendered [here](https://anaconda.org/conda-forge/spaghetti).
